# Generated by Django 4.2.4 on 2023-09-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='power',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='name',
        ),
    ]
